### ISSUE TITLE
funciona ainda?

### ISSUE THREAD

**Issue by Fuckingnameless** [felipemarinho97/torrent-indexer#19]
eu tento entrar nos links da descrição estão todos fora do ar?

**Comment by felipemarinho97** [comment]
> Warning
The instance running at https://torrent-indexer.darklyn.org/ is my personal instance and it is not guaranteed to be up all the time. Also, for better availability, I recommend deploying your own instance because the Cloudflare protection may block requests from indexed sites if too many requests are made in a short period of time from the same IP.
If I notice that the instance is being used a lot, I may block requests from Jackett to avoid overloading the server without prior notice.

☝️
